### ISSUE TITLE
Attachments lost on references with spaces

### ISSUE THREAD

**Issue by shepster** [bernardoamc/obsidian_bear#1]
First off, thank you for making this importer available to the community!

I just did my first import and I noticed an issue. Any of my notes that had a space in them did not get their attachement correctly linked.

This is the file ` /Users/jeff/Dropbox/bearExport2/DnD/PC/Hemlock Underleaf.md`
```
# Hemlock Underleaf
![[attachments/Hemlock%20Underleaf/Untitled.jpg]]
(Craig) Male half-elf druid (circle of the moon)

#DnD/PC
```
Another import tool parsed the image correctly, but it used the reference format `![](attachments/Hemlock%20Underleaf/Untitled.jpg)`

While this seems to be an Obsidian bug, looking at Markdown documentation, is seems that the proper format for image references is `![alt-text](path/to/imgage.png)`

**Comment by bernardoamc** [comment]
Hi @shepster, thanks for the report!

I've replicated the report and will work on a fix so this doesn't happen in future imports. The example helped a lot. :) 

The issue here is that white space got replaced with a `%20`. A short term fix is just to manually remove the `%20` and replace it with a proper white space.

From `![[attachments/Hemlock%20Underleaf/Untitled.jpg]]` to `![[attachments/Hemlock Underleaf/Untitled.jpg]]`

> While this seems to be an Obsidian bug, looking at Markdown documentation, is seems that the proper format for image references is ![alt-text](path/to/imgage.png)

Yeah, this is an Obsidian "quirk". The attachment format is in the form of: `![[path/to/image.jpg]]`

**Comment by bernardoamc** [comment]
@shepster the issue should be fixed, feel free to reopen this issue or create a new one if you run into a similar issue when re importing. 

Thank you! :)
